# Generated by Django 3.2 on 2024-12-20 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nitApp', '0002_auto_20241221_0333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fnamee',
            new_name='fname',
        ),
    ]
